# BigDataSpark/docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user_bd
      POSTGRES_PASSWORD: password_bd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./scripts/02_load_csv_data.sh:/docker-entrypoint-initdb.d/02_load_csv_data.sh   
      - ./исходные данные:/data_csv_for_docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_bd -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spark-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface for queries
      - "9000:9000" # Native TCP interface
      - "9009:9009" # For replication (optional)
    mem_limit: 2g
    volumes:
    - ./clickhouse/:/etc/clickhouse-server/users.d
    - clickhouse_data:/var/lib/clickhouse
    healthcheck: 
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spark-network

  mongo:
    image: mongo:6.0
    container_name: mongo_ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    networks:
      - spark-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  spark-master:
    image: bitnami/spark:3.4.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master communication port
    networks:
      - spark-network
    volumes:
      - ./jars:/home/jovyan/jars


  spark-worker:
    image: bitnami/spark:3.4.0
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes: 
      - ./jars:/home/jovyan/jars 


  jupyter-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-notebook
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - JUPYTER_ENABLE_LAB=yes
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=mydatabase 
      - POSTGRES_PASSWORD=password
    ports:
      - "8888:8888" 
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jars:/home/jovyan/jars
      - ./исходные данные:/data_csv_for_docker
      - ./scripts/run_all.sh:/home/jovyan/run_all.sh       
    depends_on:
      - spark-master
      - db
      - clickhouse
      - mongo
    networks:
      - spark-network

volumes:
  pgdata:
  clickhouse_data:
  mongo_data:

networks:
  spark-network:
    driver: bridge